name: Next.js CI/CD

on:
  push:
    branches: ["aws-deploy"]
  pull_request:
    branches: ["aws-deploy"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Create .env.production file
        run: |
          echo "NEXT_PUBLIC_GISCUS_REPO=${{ secrets.GISCUS_REPO }}" >> .env.production
          echo "NEXT_PUBLIC_GISCUS_REPO_ID=${{ secrets.GISCUS_REPO_ID }}" >> .env.production
          echo "NEXT_PUBLIC_GISCUS_CATEGORY=${{ secrets.GISCUS_CATEGORY }}" >> .env.production
          echo "NEXT_PUBLIC_GISCUS_CATEGORY_ID=${{ secrets.GISCUS_CATEGORY_ID }}" >> .env.production
          echo "API_URL=${{ secrets.API_URL }}" >> .env.production
      - name: Build Next.js
        run: npm run build
      - name: Prepare deploy package
        run: |
          mkdir deploy
          cp -r .next public package*.json .env.production deploy/
          cd deploy
          tar -czf app.tar.gz *
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-app-deploy
          path: deploy/app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: next-app-deploy
      - name: Stop docker container
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          port: ${{ secrets.AWS_SERVER_PORT }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SERVER_KEY }}
          proxy_host: ${{ secrets.AWS_PROXY_SERVER_HOST }}
          proxy_port: ${{ secrets.AWS_PROXY_SERVER_PORT }}
          proxy_username: ${{ secrets.AWS_PROXY_SERVER_USER }}
          proxy_key: ${{ secrets.AWS_PROXY_SERVER_KEY }}
          script: |
            cd /home/ec2-user
            if [ -f ./build/.env.production ]; then
              docker-compose down
            fi
            cd /home/ec2-user/build
            rm -rf *
      - name: Copy tar to Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          port: ${{ secrets.AWS_SERVER_PORT }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SERVER_KEY }}
          proxy_host: ${{ secrets.AWS_PROXY_SERVER_HOST }}
          proxy_port: ${{ secrets.AWS_PROXY_SERVER_PORT }}
          proxy_username: ${{ secrets.AWS_PROXY_SERVER_USER }}
          proxy_key: ${{ secrets.AWS_PROXY_SERVER_KEY }}
          source: "app.tar.gz"
          target: "/home/ec2-user/build"
      - name: Start docker container
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          port: ${{ secrets.AWS_SERVER_PORT }}
          username: ${{ secrets.AWS_SERVER_USER }}
          key: ${{ secrets.AWS_SERVER_KEY }}
          proxy_host: ${{ secrets.AWS_PROXY_SERVER_HOST }}
          proxy_port: ${{ secrets.AWS_PROXY_SERVER_PORT }}
          proxy_username: ${{ secrets.AWS_PROXY_SERVER_USER }}
          proxy_key: ${{ secrets.AWS_PROXY_SERVER_KEY }}
          script: |
            cd /home/ec2-user/build
            tar -xzf app.tar.gz
            cd /home/ec2-user
            docker-compose up -d
